// NFL: declared, not yet playable.
//
// This file exists so the shape of the work is visible and the UI can offer
// the sport the moment it's real, rather than the tile being hardcoded
// "Coming soon" markup that somebody has to remember to go and change.
// `live: false` is the only thing keeping it out of play - every screen reads
// that flag, so flipping it is what ships NFL, and nothing flips it until the
// pieces below exist.
//
// WHY NFL CANNOT REUSE THE NBA ENGINE
//
// js/sports/nba/engine.js is not a generic sports simulator. It models five positions
// guarding five positions over four 48-minute quarters, and every number in
// it - SCORING_K, the rebound and assist matchup factors, the fatigue curve,
// the 1.55 combined scoring ceiling - is solved against basketball box
// scores by tools/calibrate-*.mjs. Football has no equivalent of a positional
// matchup: a quarterback is not "guarded" by the opposing quarterback, and
// production comes from a drive model, not from minutes shared at a position.
//
// So NFL gets its own simulate(), and this registry is what lets the two
// coexist instead of one being bent into the other's shape.

// Generated by tools/build-nfl-data.mjs from nflverse season exports. Two
// files because they are two shapes: a quarterback has a passing line, a
// secondary has a unit line, and flattening them into one table would make
// every reader guard against the other's columns.
import { ROWS as NFL_PLAYERS } from "../../../data/nfl-players.js";
import { ROWS as NFL_UNITS } from "../../../data/nfl-units.js";
import { computeDatasetStats, simulate } from "./engine.js";

/** Built once, on first use. See NFL.computeDatasetStats below for why this
 * cannot be rebuilt per call. */
let ratingCtx = null;
import { rateEntry } from "./units.js";
import { buildRecap, buildGameScript, buildPostGameAnalysis } from "./recap.js";
import { draftGrade } from "./draftgrade.js";
import { TACTICS, DEFAULT_TACTIC, tacticById, randomTacticChoices } from "./tactics.js";

// The football career, rung by rung - the counterpart to basketball's ladder
// in js/sports/nba/index.js, and deliberately built on the SAME percentile
// bands. A rank means the same thing in both sports (top X% of the player
// base by win rate); only what it is called changes, because "NBA MVP" says
// nothing to a football player and "Heisman" says nothing to a basketball one.
//
// Same shape to the arc, too: it starts where everyone actually starts, runs
// through the levels a real career passes, and narrows hard at the top. Bands
// widen at the bottom and tighten above the 80th percentile on purpose - most
// people never leave youth football, and "Hall of Fame" should mean it.
const TIERS = [
  { name: "Pop Warner", minPercentile: 0 },
  { name: "Middle School", minPercentile: 5 },
  { name: "JV", minPercentile: 10 },
  { name: "Varsity", minPercentile: 16 },
  { name: "All-District", minPercentile: 22 },
  { name: "All-State", minPercentile: 28 },
  { name: "Juco", minPercentile: 35 },
  { name: "FCS", minPercentile: 42 },
  { name: "FBS Starter", minPercentile: 49 },
  { name: "Power Conference", minPercentile: 56 },
  { name: "All-Conference", minPercentile: 62 },
  { name: "Bowl Game", minPercentile: 68 },
  { name: "All-American", minPercentile: 73 },
  { name: "Heisman Finalist", minPercentile: 78 },
  { name: "NFL Draftee", minPercentile: 82 },
  { name: "Rookie of the Year", minPercentile: 85.5 },
  { name: "Pro Bowler", minPercentile: 88.5 },
  { name: "All-Pro", minPercentile: 91 },
  { name: "NFL MVP", minPercentile: 93.5 },
  { name: "Super Bowl Champion", minPercentile: 96 },
  { name: "Hall of Fame", minPercentile: 98 },
  { name: "Legend", minPercentile: 99.5 },
];

// Written against the roster the game actually deals now. The rules a player
// has to be TOLD - rather than left to discover by having a pick rejected -
// are that five slots are units and that you claim one by naming a single
// player from it. Neither is guessable from a board that just says "LB".
const HOW_TO_PLAY = [
  ["The draft", "Every round rolls one team-and-era roster - say the 1985 Chicago Bears - and both sides draft from it. Same options, same board: it comes down to who knows the team better."],
  ["Units, not just players", "Offence is drafted man by man - quarterback, running back, three receivers, tight end. The line and the whole defence are drafted as UNITS: the offensive line, the defensive line, the linebackers, the corners, the safeties, special teams. Nobody remembers the '85 Bears' third safety; everyone remembers that defence."],
  ["ONE name takes a whole unit", "This is the part to know before your first draft. To draft a unit you name any ONE player from it - type Urlacher and the 2006 Bears linebackers are yours, all four of them. Sherman, Thomas or Chancellor each take the 2013 Seahawks secondary. You never have to name eleven people, and you are never asked which one you meant."],
  ["The offensive line is the exception", "Type \"Offensive Line\" for that slot. The stat sheets football keeps do not name the linemen who played, so there is nobody to type - it is the one unit claimed by what it is rather than by who was in it."],
  ["Your roster", "Twelve picks: seven on offence - quarterback, running back, three receivers, tight end, offensive line - and five on defence and special teams. Field goals decide real games, so the kicking unit is a real choice rather than an afterthought."],
  ["Gameplan", "Once both rosters are set you pick one of three gameplans offered at random. Each trades something for something, and how much a gameplan is worth depends on WHO YOU DREW: Ground and Pound with Lamar Jackson under centre is a different thing than with a quarterback who cannot run. There is no best one, only a best one for your lineup."],
  ["Coin toss", "A toss decides who receives. Electing to kick hands over the first drive to take the ball out of halftime - what a coach with a real defence does. Tied after four quarters and both sides get a possession in overtime, repeating until someone leads."],
  ["Modes", "Quick Play is a relaxed short-roster game against the bot. Ranked Practice is the full experience against the bot. Ranked is a real opponent and the only mode that moves your record."],
];

export const NFL = {
  id: "nfl",
  name: "NFL",
  icon: "🏈",

  // LIVE, and deliberately ahead of its calibration. The balance levers in
  // constants.js are still the provisional placeholders and all eight
  // gamestyles sit at pts 1.0, so no style is secretly strongest but none of
  // them are solved either. Shipped this way on purpose: the fastest way to
  // find out whether a football sim feels like football is to let people play
  // it, and NFL ELO can be reset once the calibrators have run.
  live: true,
  // Selectable without being playable: you can switch the whole app to NFL and
  // see its dashboard, eras, labels and branding, which is what building those
  // screens requires. Start Draft stays disabled - see isSelectable() in
  // js/sports/index.js for why this is a second flag rather than loosening
  // `live`, which everything that touches an engine still reads.
  preview: true,
  status: "In development",

  // Football blue - the app's original palette, kept here because it suits
  // this sport. Every sport declares its own; see the NBA module for the four
  // custom properties these map onto.
  //
  // accentContrast is white rather than the dark navy the rest of the app used
  // to pair with this blue: as text on a solid accent fill the navy comes in
  // at 4.1:1, under the 4.5:1 floor, and white clears it at 4.7:1.
  theme: {
    accent: "#2f6fe0",
    accentBright: "#62a0ff",
    accentRgb: "47, 111, 224",
    accentContrast: "#ffffff",
  },

  labels: {
    squad: "roster",
    squadPlural: "rosters",
    group: "era",
    unit: "snaps",
    period: "quarter",
    periodPlural: "quarters",
    scoreVerb: "scored",
  },

  // Seven individuals and five units. The provisional lineup this replaces
  // (QB, RB1, RB2, WR1, WR2, TE, FLEX, K, DEF, BENCH1) modelled fantasy
  // football rather than football - a FLEX and a lone kicker are fantasy
  // constructs, and one catch-all DEF slot throws away the whole point of
  // drafting a defence in units.
  //
  // THREE receivers, not two. Eleven personnel - one back, one tight end,
  // three wide - has been the league's base offence for over a decade; a
  // two-receiver ranked roster would be drafting a personnel package the
  // modern game only uses part-time. It also makes the third receiver a real
  // decision rather than a luxury, which is where a lot of the good arguments
  // about an offence actually live.
  //
  // Twelve rather than basketball's ten because dropping special teams to hit
  // a round number would be a mistake: field goals decide real games, and a
  // game where kicking never matters is missing a third of its endings.
  slots: {
    quickPlay: ["QB", "RB", "WR", "TE", "OL", "DEF"],
    ranked: ["QB", "RB", "WR1", "WR2", "WR3", "TE", "OL", "DL", "LB", "CB", "S", "ST"],
    starters: ["QB", "RB", "WR1", "WR2", "WR3", "TE", "OL", "DL", "LB", "CB", "S", "ST"],
    // No bench. Football substitutes by unit and by situation, not by a sixth
    // man, so the roster is twelve starters and the depth term lives on the
    // units themselves (see `depth` in data/nfl-units.js).
    bench: [],
  },

  // Plain decades, not the rule-change brackets docs/nfl-plan.md first
  // proposed (Leather, Smashmouth, Air It Out). nflverse - the only bulk,
  // machine-readable source - starts in 1999, so pre-2000 football cannot be
  // imported at all and those brackets would have been empty shelves.
  //
  // One wide bracket plus three narrow ones, matching NBA's shape, which is
  // what lets the era-mastery banner ladder work over either sport unchanged.
  eras: [
    { id: "all", label: "All Years", emoji: "🏈", decades: null, blurb: "Every team, every season since 2000." },
    { id: "2000s", label: "2000s", emoji: "📼", decades: ["2000s"], blurb: "Dynasty Patriots, the Greatest Show on Turf, smashmouth NFC North." },
    { id: "2010s", label: "2010s", emoji: "📱", decades: ["2010s"], blurb: "Legion of Boom, Megatron, the read-option arrives." },
    { id: "2020s", label: "2020s", emoji: "🚀", decades: ["2020s"], blurb: "Mahomes, the RPO era, fourth-down aggression." },
  ],
  defaultEra: "all",
  eraById: (id) => NFL.eras.find((e) => e.id === id) || NFL.eras[0],

  // Its own table, not a sport column on `players`. Football's per-game
  // columns (pass/rush/rec yards, touchdowns, interceptions, sacks) share
  // almost nothing with basketball's, so one table would be two disjoint sets
  // of mostly-null columns and every query would carry a filter it could
  // forget. See db/migrations for the schema.
  table: "nfl_players",
  statKeys: ["pass_yds", "rush_yds", "rec_yds", "tds", "turnovers"],
  // Kept in step with statLabels below: these are the columns a football box
  // score will carry, and the profile's records are read straight off them.
  lineKeys: ["pass_yds", "pass_tds", "rush_yds", "rush_tds", "rec_yds", "rec_tds", "ints", "fumbles", "fgs"],

  // Placeholders, and honestly so: no NFL game has been simulated, so every
  // one of these reads as a dash on the profile. They are declared now because
  // the profile screen builds its Top Performances list from this - without it
  // the NFL subtab would have nothing to draw at all, and showing what WILL be
  // tracked is more useful than an empty panel.
  //
  // Both sides of the ball, because football records that only covered offence
  // would leave half a roster with nothing to chase. Keyed to match what a
  // football box score will carry (lineKeys above), so when the engine lands
  // these start filling in rather than needing renaming.
  statLabels: {
    pass_yds: "Passing Yards",
    pass_tds: "Passing TDs",
    rush_yds: "Rushing Yards",
    rush_tds: "Rushing TDs",
    rec_yds: "Receiving Yards",
    rec_tds: "Receiving TDs",
    ints: "Interceptions",
    fumbles: "Fumbles Recovered",
    fgs: "Field Goals",
  },

  // ---- Not built yet ------------------------------------------------------
  // Each of these throws rather than returning something plausible. A stub
  // that quietly returns an empty roster or a 0-0 result would let a
  // half-wired NFL reach a player looking like a working game, and the bug
  // would surface as "the sim is broken" rather than "this isn't finished".
  // Real data now (tools/build-nfl-data.mjs). Individuals and units are two
  // generated files because they are two different shapes - a quarterback has
  // a passing line, a secondary has a unit line - and flattening them into one
  // table would make every reader guard against the other's columns.
  players: () => NFL_PLAYERS,
  units: () => NFL_UNITS,

  /** Everything draftable in one era: individuals and units together, since
   * the draft board offers them side by side. "all" is every season. */
  playersInEra: (eraId) => {
    const era = NFL.eraById(eraId);
    const inEra = (row) => !era.decades || era.decades.includes(row.era);
    return [...NFL_PLAYERS.filter(inEra), ...NFL_UNITS.filter(inEra)];
  },

  // MEMOISED, and it has to be. Building this sorts a composite score for
  // every one of ~9,100 players and ~4,800 units. rate() is called once per
  // row the draft board renders, and each call used to rebuild the whole
  // index - thousands of full sorts on one click, which froze the tab hard
  // enough that Quick Play never appeared. The dataset is generated and
  // immutable at runtime, so one build lasts the session.
  computeDatasetStats: () => (ratingCtx ||= computeDatasetStats(NFL_PLAYERS, NFL_UNITS)),
  simulate: (rosterA, rosterB, stats, opts) => simulate(rosterA, rosterB, stats, opts),

  // Football has no minutes. Everyone on a drafted roster plays every snap of
  // his side of the ball - there is no rotation to decide and no bench to
  // bring on, so the rotation screen has nothing to ask. Returning an empty
  // map rather than throwing is what lets shared code run the same flow for
  // both sports without branching on which one it is.
  defaultMinutes: () => ({}),
  botMinutes: () => ({}),
  defaultMatchups: () => ({}),

  // The draft-board seams shared code reads (see js/sports/nba/index.js for
  // the working versions). groupKey is "era" rather than basketball's
  // "decade" because football's brackets follow rule changes.
  groupKey: "era",
  // What the draft board sorts and grades by. Percentile among others at the
  // same position or in the same unit group, so a quarterback and a secondary
  // are comparable - see js/sports/nfl/units.js for why percentile rather than
  // an invented rating.
  rate: (entry, ctx) => rateEntry(entry, ctx ?? NFL.computeDatasetStats()),
  // Strips the ordinal so WR1/WR2/WR3 all resolve to WR - a receiver's data
  // says "WR", not "WR2", and without this every numbered slot would reject
  // every player eligible for it. Same rule NBA uses; it only looked like an
  // identity function while no slot had a number in it.
  /** Football's version. A quarterback, a back and a secondary have nothing
   * in common statistically, so each says what it is actually good at rather
   * than being forced through one shared set of columns. */
  cardStatLine: (p) => {
    const n = (v, d = 1) => (Number(v) || 0).toFixed(d);
    if (p.group) {
      const depth = `${p.depth} deep`;
      if (p.group === "ST") return `${depth} · ${n(100 * (p.fg_pct || 0), 0)}% FG · ${n(p.fg_att)} att`;
      if (p.group === "OL") return `${depth} · ${n(p.sacks_allowed)} sk allowed · ${n(p.ypc)} ypc`;
      return `${depth} · ${n(p.tackles)} tkl · ${n(p.sacks)} sk · ${n(p.ints, 2)} int`;
    }
    const pos = (p.pos || [])[0];
    if (pos === "QB") return `${n(p.pass_yds, 0)} pass yds · ${n(p.pass_td, 1)} TD · ${n(p.ints, 1)} INT`;
    if (pos === "RB") return `${n(p.rush_yds, 0)} rush yds · ${n(p.rush_td)} TD · ${n(p.rec)} rec`;
    return `${n(p.rec)} rec · ${n(p.rec_yds, 0)} yds · ${n(p.rec_td)} TD`;
  },
  basePosition: (slot) => slot.replace(/\d+$/, ""),
  isBenchSlot: (slot) => slot.startsWith("BENCH"),
  orderedRosterSlots: (roster) => Object.keys(roster).filter((s) => roster[s]),
  minutesRangeFor: () => ({ min: 0, max: 0 }),
  rotationBudget: 0,

  // Narrative and grading. Stubs live in the sibling files named below; these
  // throw for the same reason the simulation stubs do - a recap that returned
  // empty prose would look like a working game with nothing to say.
  buildRecap: (result, rosterA, rosterB, labelA, labelB) =>
    buildRecap(result, rosterA, rosterB, labelA, labelB),
  buildGameScript: (result) => buildGameScript(result),
  buildPostGameAnalysis: (result, side) => buildPostGameAnalysis(result, side),
  draftGrade: (roster, ctx, forfeits) => draftGrade(roster, ctx ?? NFL.computeDatasetStats(), forfeits),
  rotationHint: () => null,
  // Football's counterpart to basketball's counterplay read: how your roster
  // stacks against theirs, side of the ball by side of the ball.
  draftAnalysis: (roster, oppRoster, ctx, forfeits) =>
    draftGrade(roster, ctx ?? NFL.computeDatasetStats(), forfeits),
  shotLine: () => null,
  formatShotLine: () => "",

  // The ladder and the explanation are real even though the game is not -
  // they are the two screens you can look at today, and there is nothing
  // stopping them being finished.
  tiers: TIERS,
  howToPlay: HOW_TO_PLAY,

  tactics: TACTICS,
  defaultTactic: DEFAULT_TACTIC,
  tacticById,
  randomTacticChoices,

  /** What still has to exist before `live` can flip. Rendered on the locked
   * tile in dev builds, so the remaining work is visible in the product
   * rather than only in this comment. */
  todo: [
    "Import per-game player data into an nfl_players table",
    "Aggregate defensive position groups into draftable units (units.js)",
    "Author era brackets that follow rule changes, not decades",
    "Write a drive-based simulation engine and calibrate it",
    "Author gamestyles and solve their multipliers the way tactics.js is",
    "Add NFL badges and make the franchise banners earnable",
  ],
};

export default NFL;
