// NFL: declared, not yet playable.
//
// This file exists so the shape of the work is visible and the UI can offer
// the sport the moment it's real, rather than the tile being hardcoded
// "Coming soon" markup that somebody has to remember to go and change.
// `live: false` is the only thing keeping it out of play - every screen reads
// that flag, so flipping it is what ships NFL, and nothing flips it until the
// pieces below exist.
//
// WHY NFL CANNOT REUSE THE NBA ENGINE
//
// js/sports/nba/engine.js is not a generic sports simulator. It models five positions
// guarding five positions over four 48-minute quarters, and every number in
// it - SCORING_K, the rebound and assist matchup factors, the fatigue curve,
// the 1.55 combined scoring ceiling - is solved against basketball box
// scores by tools/calibrate-*.mjs. Football has no equivalent of a positional
// matchup: a quarterback is not "guarded" by the opposing quarterback, and
// production comes from a drive model, not from minutes shared at a position.
//
// So NFL gets its own simulate(), and this registry is what lets the two
// coexist instead of one being bent into the other's shape.

// Generated by tools/build-nfl-data.mjs from nflverse season exports. Two
// files because they are two shapes: a quarterback has a passing line, a
// secondary has a unit line, and flattening them into one table would make
// every reader guard against the other's columns.
// LOADED ON DEMAND, NOT ON BOOT.
//
// These two files are 4.2MB between them - larger than everything else the app
// loads put together. Imported at module scope they were fetched, parsed and
// evaluated by every single page load, including the overwhelming majority
// that only ever open basketball. Nobody drafting an NBA roster needs a list
// of every defensive unit in football history.
//
// So they arrive when football is CHOSEN. `preload()` is idempotent and
// returns the same promise to concurrent callers, so a double click on the
// sport tile fetches once.
//
// Deliberately NOT falling back to an empty list when the data has not
// arrived: an empty roster pool would look like a sport with no players
// rather than a bug, and the whole point of CLAUDE.md's rule about silent
// failures is that a plausible-looking wrong answer is the expensive kind.
// Calling these before preload() is a programming error and says so.
let NFL_PLAYERS = null;
let NFL_UNITS = null;
let loading = null;

function loaded() {
  if (!NFL_PLAYERS || !NFL_UNITS) {
    throw new Error(
      "NFL data has not been loaded. Call NFL.preload() (or ensureSportData('nfl')) before using football's players."
    );
  }
}

async function preload() {
  if (NFL_PLAYERS && NFL_UNITS) return;
  if (!loading) {
    loading = Promise.all([
      import("../../../data/nfl-players.js"),
      import("../../../data/nfl-units.js"),
    ]).then(([players, units]) => {
      NFL_PLAYERS = players.ROWS;
      NFL_UNITS = units.ROWS;
    }).catch((error) => {
      // A failed load must not leave a permanently poisoned promise - the next
      // attempt should be able to try again rather than reject forever.
      loading = null;
      throw error;
    });
  }
  return loading;
}
import { computeDatasetStats, simulate } from "./engine.js";

/** Built once, on first use. See NFL.computeDatasetStats below for why this
 * cannot be rebuilt per call. */
let ratingCtx = null;
import { rateEntry } from "./units.js";
import { buildRecap, buildGameScript, buildPostGameAnalysis, HIGHLIGHTS } from "./recap.js";
import { draftGrade } from "./draftgrade.js";
import {
  OFFENSIVE_PLANS, DEFENSIVE_PLANS, STRATEGY_GROUPS, DEFAULT_STRATEGY,
  planFor, normalizeStrategy, plansFor, randomStrategy, formatStrategy,
  serializeStrategy, parseStrategy,
} from "./tactics.js";
import { buildTimeline, createLiveState, applyEvent, liveBox, liveScore } from "./playback.js";

/** The order a football roster is READ in, which is not the order it is
 * drafted in. Offence before defence, and inside offence the skill positions
 * in depth-chart order - a box score that opens on a wide receiver reads as a
 * bug even when every number in it is right. Covers both roster shapes: Quick
 * Play's bare WR and ranked's WR1/WR2/WR3. */
const LINEUP_ORDER = [
  "QB", "RB", "WR", "WR1", "WR2", "WR3", "TE", "FLEX", "OL",
  "DL", "LB", "CB", "S", "DEF", "ST",
];

// The football career, rung by rung - the counterpart to basketball's ladder
// in js/sports/nba/index.js, and deliberately built on the SAME percentile
// bands. A rank means the same thing in both sports (top X% of the player
// base by win rate); only what it is called changes, because "NBA MVP" says
// nothing to a football player and "Heisman" says nothing to a basketball one.
//
// Same shape to the arc, too: it starts where everyone actually starts, runs
// through the levels a real career passes, and narrows hard at the top. Bands
// widen at the bottom and tighten above the 80th percentile on purpose - most
// people never leave youth football, and "Hall of Fame" should mean it.

const TIERS = [
  { name: "Pop Warner", minPercentile: 0 },
  { name: "Middle School", minPercentile: 5 },
  { name: "JV", minPercentile: 10 },
  { name: "Varsity", minPercentile: 16 },
  { name: "All-District", minPercentile: 22 },
  { name: "All-State", minPercentile: 28 },
  { name: "Juco", minPercentile: 35 },
  { name: "FCS", minPercentile: 42 },
  { name: "FBS Starter", minPercentile: 49 },
  { name: "Power Conference", minPercentile: 56 },
  { name: "All-Conference", minPercentile: 62 },
  { name: "Bowl Game", minPercentile: 68 },
  { name: "All-American", minPercentile: 73 },
  { name: "Heisman Finalist", minPercentile: 78 },
  { name: "NFL Draftee", minPercentile: 82 },
  { name: "Rookie of the Year", minPercentile: 85.5 },
  { name: "Pro Bowler", minPercentile: 88.5 },
  { name: "All-Pro", minPercentile: 91 },
  { name: "NFL MVP", minPercentile: 93.5 },
  { name: "Super Bowl Champion", minPercentile: 96 },
  { name: "Hall of Fame", minPercentile: 98 },
  { name: "Legend", minPercentile: 99.5 },
];

// Written against the roster the game actually deals now. The rules a player
// has to be TOLD - rather than left to discover by having a pick rejected -
// are that five slots are units and that you claim one by naming a single
// player from it. Neither is guessable from a board that just says "LB".
// Short on purpose - see the same note in js/sports/nba/index.js. The two
// rules that cannot be guessed from the board (one name takes a unit, and the
// offensive line is the exception) stay; everything else is trimmed to a line.
const HOW_TO_PLAY = [
  ["The draft", "Each round rolls one team and era - say the 1985 Bears - and you both draft from it."],
  ["Units, not just players", "You draft the skill positions man by man. The line and the whole defence go as units."],
  ["One name takes a unit", "Type ANY player in it. Urlacher takes the 2006 Bears linebackers - all four. You never name eleven people."],
  ["Except the line", "Type \"Offensive Line\" for that slot. Football's stat sheets name no linemen, so there is nobody to type."],
  ["Your roster", "Twelve picks: seven on offence, five on defence and special teams."],
  ["Game plan", "Three offered at random, and what one is worth depends on who you drew - Ground and Pound wants a running quarterback."],
  ["Coin toss", "Winner receives or kicks. Tied after four quarters, both sides get a possession in overtime."],
  ["Modes", "Quick Play is casual. Ranked Practice is the full game against a bot. Ranked moves your record."],
];

export const NFL = {
  id: "nfl",
  name: "NFL",
  icon: "🏈",

  // LIVE, and deliberately ahead of its calibration. The balance levers in
  // constants.js are still the provisional placeholders and all eight
  // gamestyles sit at pts 1.0, so no style is secretly strongest but none of
  // them are solved either. Shipped this way on purpose: the fastest way to
  // find out whether a football sim feels like football is to let people play
  // it, and NFL ELO can be reset once the calibrators have run.
  live: true,
  // Selectable without being playable: you can switch the whole app to NFL and
  // see its dashboard, eras, labels and branding, which is what building those
  // screens requires. Start Draft stays disabled - see isSelectable() in
  // js/sports/index.js for why this is a second flag rather than loosening
  // `live`, which everything that touches an engine still reads.
  preview: true,
  status: "In development",

  // Football blue - the app's original palette, kept here because it suits
  // this sport. Every sport declares its own; see the NBA module for the four
  // custom properties these map onto.
  //
  // accentContrast is white rather than the dark navy the rest of the app used
  // to pair with this blue: as text on a solid accent fill the navy comes in
  // at 4.1:1, under the 4.5:1 floor, and white clears it at 4.7:1.
  theme: {
    accent: "#2f6fe0",
    accentBright: "#62a0ff",
    accentRgb: "47, 111, 224",
    accentContrast: "#ffffff",
  },

  labels: {
    squad: "roster",
    squadPlural: "rosters",
    group: "era",
    unit: "snaps",
    period: "quarter",
    periodPlural: "quarters",
    scoreVerb: "scored",
    opening: "kickoff",
  },

  // Football is watched on a field, and it is watched as a TIMELINE - a
  // sequence of events each worth its own amount of time. Both are declared
  // here rather than discovered by shared code, which is what keeps js/main.js
  // from importing a sport (see CLAUDE.md).
  //
  // buildTimeline is optional in the contract: a sport that does not declare
  // one is revealed by whatever its stage already does, which is what
  // basketball's quarter reveal is.
  // createLiveState/applyEvent are what make the live table a LEDGER rather
  // than a reveal: shared playback folds one event at a time into this state
  // instead of accumulating a finished quarter line the moment the quarter
  // starts. A sport that does not declare them keeps the period-reveal path,
  // which is what basketball still uses.
  presentation: { stage: "field", buildTimeline, createLiveState, applyEvent, liveBox, liveScore },

  // Seven individuals and five units. The provisional lineup this replaces
  // (QB, RB1, RB2, WR1, WR2, TE, FLEX, K, DEF, BENCH1) modelled fantasy
  // football rather than football - a FLEX and a lone kicker are fantasy
  // constructs, and one catch-all DEF slot throws away the whole point of
  // drafting a defence in units.
  //
  // THREE receivers, not two. Eleven personnel - one back, one tight end,
  // three wide - has been the league's base offence for over a decade; a
  // two-receiver ranked roster would be drafting a personnel package the
  // modern game only uses part-time. It also makes the third receiver a real
  // decision rather than a luxury, which is where a lot of the good arguments
  // about an offence actually live.
  //
  // Twelve rather than basketball's ten because dropping special teams to hit
  // a round number would be a mistake: field goals decide real games, and a
  // game where kicking never matters is missing a third of its endings.
  slots: {
    quickPlay: ["QB", "RB", "WR", "TE", "OL", "DEF"],
    ranked: ["QB", "RB", "WR1", "WR2", "WR3", "TE", "OL", "DL", "LB", "CB", "S", "ST"],
    starters: ["QB", "RB", "WR1", "WR2", "WR3", "TE", "OL", "DL", "LB", "CB", "S", "ST"],
    // No bench. Football substitutes by unit and by situation, not by a sixth
    // man, so the roster is twelve starters and the depth term lives on the
    // units themselves (see `depth` in data/nfl-units.js).
    bench: [],
  },

  // Plain decades, not the rule-change brackets docs/nfl-plan.md first
  // proposed (Leather, Smashmouth, Air It Out). nflverse - the only bulk,
  // machine-readable source - starts in 1999, so pre-2000 football cannot be
  // imported at all and those brackets would have been empty shelves.
  //
  // One wide bracket plus three narrow ones, matching NBA's shape, which is
  // what lets the era-mastery banner ladder work over either sport unchanged.
  eras: [
    { id: "all", label: "All Years", emoji: "🏈", decades: null, blurb: "Every team, every season since 2000." },
    { id: "2000s", label: "2000s", emoji: "📼", decades: ["2000s"], blurb: "Dynasty Patriots, the Greatest Show on Turf, smashmouth NFC North." },
    { id: "2010s", label: "2010s", emoji: "📱", decades: ["2010s"], blurb: "Legion of Boom, Megatron, the read-option arrives." },
    { id: "2020s", label: "2020s", emoji: "🚀", decades: ["2020s"], blurb: "Mahomes, the RPO era, fourth-down aggression." },
  ],
  defaultEra: "all",
  eraById: (id) => NFL.eras.find((e) => e.id === id) || NFL.eras[0],

  // Its own table, not a sport column on `players`. Football's per-game
  // columns (pass/rush/rec yards, touchdowns, interceptions, sacks) share
  // almost nothing with basketball's, so one table would be two disjoint sets
  // of mostly-null columns and every query would carry a filter it could
  // forget. See db/migrations for the schema.
  table: "nfl_players",
  statKeys: ["pass_yds", "rush_yds", "rec_yds", "tds", "turnovers"],
  // Kept in step with statLabels below: these are the columns a football box
  // score will carry, and the profile's records are read straight off them.
  // Every column the box score draws needs a key here, or the live table has
  // nowhere to accumulate it and sits at zero all game while the header
  // promises a number. comp/att/rec were missing exactly that way.
  // `carries` and `fga` accumulate but are NOT in statLabels, for the same
  // reason `att` is not: these keys become personal bests, and a record for
  // most carries or most field goals missed rewards volume and failure rather
  // than anything anyone would want to chase.
  lineKeys: ["comp", "att", "pass_yds", "pass_tds", "carries", "rush_yds", "rush_tds",
             "rec", "rec_yds", "rec_tds", "ints", "fumbles", "fgs", "fga"],

  // Placeholders, and honestly so: no NFL game has been simulated, so every
  // one of these reads as a dash on the profile. They are declared now because
  // the profile screen builds its Top Performances list from this - without it
  // the NFL subtab would have nothing to draw at all, and showing what WILL be
  // tracked is more useful than an empty panel.
  //
  // Both sides of the ball, because football records that only covered offence
  // would leave half a roster with nothing to chase. Keyed to match what a
  // football box score will carry (lineKeys above), so when the engine lands
  // these start filling in rather than needing renaming.
  statLabels: {
    pass_yds: "Passing Yards",
    pass_tds: "Passing TDs",
    rush_yds: "Rushing Yards",
    rush_tds: "Rushing TDs",
    rec_yds: "Receiving Yards",
    rec_tds: "Receiving TDs",
    ints: "Interceptions",
    fumbles: "Fumbles Recovered",
    fgs: "Field Goals",
    comp: "Completions",
    rec: "Receptions",
    // `att` is deliberately absent. These keys become PERSONAL BESTS, and a
    // record for most passes thrown rewards volume and losing rather than
    // anything anyone would want to chase.
  },

  // ---- Not built yet ------------------------------------------------------
  // Each of these throws rather than returning something plausible. A stub
  // that quietly returns an empty roster or a 0-0 result would let a
  // half-wired NFL reach a player looking like a working game, and the bug
  // would surface as "the sim is broken" rather than "this isn't finished".
  // Real data now (tools/build-nfl-data.mjs). Individuals and units are two
  // generated files because they are two different shapes - a quarterback has
  // a passing line, a secondary has a unit line - and flattening them into one
  // table would make every reader guard against the other's columns.
  // BOTH kinds. Shared code draws the draft pool from players(), so returning
  // only individuals left every unit slot - OL, DL, LB, CB, S, and Quick
  // Play's DEF - with nothing eligible. The draft filled its skill positions
  // and then hung with two slots open and no legal pick on the board.
  preload,
  isLoaded: () => !!(NFL_PLAYERS && NFL_UNITS),
  players: () => (loaded(), [...NFL_PLAYERS, ...NFL_UNITS]),
  individuals: () => (loaded(), NFL_PLAYERS),
  units: () => (loaded(), NFL_UNITS),

  /** Everything draftable in one era: individuals and units together, since
   * the draft board offers them side by side. "all" is every season. */
  // Signature must match NBA's (players, eraId) - shared code calls
  // sport().playersInEra(sport().players(), game.era). NFL took only an eraId,
  // so it received the PLAYER ARRAY as its era and filtered on nothing: the era
  // picker did nothing at all and All Years drafted the same pool as 2010s.
  playersInEra: (players, eraId) => {
    const era = NFL.eraById(eraId);
    const inEra = (row) => !era?.decades || era.decades.includes(row.era);
    if (!players) loaded();
    return (players ?? [...NFL_PLAYERS, ...NFL_UNITS]).filter(inEra);
  },

  // MEMOISED, and it has to be. Building this sorts a composite score for
  // every one of ~9,100 players and ~4,800 units. rate() is called once per
  // row the draft board renders, and each call used to rebuild the whole
  // index - thousands of full sorts on one click, which froze the tab hard
  // enough that Quick Play never appeared. The dataset is generated and
  // immutable at runtime, so one build lasts the session.
  computeDatasetStats: () => (loaded(), (ratingCtx ||= computeDatasetStats(NFL_PLAYERS, NFL_UNITS))),
  simulate: (rosterA, rosterB, stats, opts) => simulate(rosterA, rosterB, stats, opts),

  // Football has no minutes. Everyone on a drafted roster plays every snap of
  // his side of the ball - there is no rotation to decide and no bench to
  // bring on, so the rotation screen has nothing to ask. Returning an empty
  // map rather than throwing is what lets shared code run the same flow for
  // both sports without branching on which one it is.
  defaultMinutes: () => ({}),
  botMinutes: () => ({}),
  // Units line up against units - nobody to assign.
  highlights: HIGHLIGHTS,
  usesMatchups: false,
  defaultMatchups: () => ({}),

  // The draft-board seams shared code reads (see js/sports/nba/index.js for
  // the working versions). groupKey is "era" rather than basketball's
  // "decade" because football's brackets follow rule changes.
  groupKey: "era",
  // What the draft board sorts and grades by. Percentile among others at the
  // same position or in the same unit group, so a quarterback and a secondary
  // are comparable - see js/sports/nfl/units.js for why percentile rather than
  // an invented rating.
  rate: (entry, ctx) => rateEntry(entry, ctx ?? NFL.computeDatasetStats()),
  // Strips the ordinal so WR1/WR2/WR3 all resolve to WR - a receiver's data
  // says "WR", not "WR2", and without this every numbered slot would reject
  // every player eligible for it. Same rule NBA uses; it only looked like an
  // identity function while no slot had a number in it.
  /** Football's version. A quarterback, a back and a secondary have nothing
   * in common statistically, so each says what it is actually good at rather
   * than being forced through one shared set of columns. */
  /** Football's box score. Passing, rushing and receiving are three different
   * jobs and get three different columns - a quarterback's line and a
   * cornerback's have almost nothing in common, which is the whole reason this
   * is per sport rather than one shared set. */
  // No made/attempted pairs - football's attempts already have their own
  // columns (COMP/ATT), so there is nothing to append.
  splitColumns: [],
  // PTS IS GONE, deliberately. Points are a football statistic - the scoreboard
  // is made of them - but they are a terrible way to read a football PLAYER.
  // A quarterback who throws for 400 and four touchdowns scores none of them,
  // so ranking a table by points put the kicker above him on any night he
  // outkicked the offence. What a football player did is yardage and scores,
  // which is what these columns are now.
  //
  // Used for personal records and for the MVP line (formatMvpStatLine reads
  // this list), so removing PTS also stops the MVP being announced with a
  // number nobody quotes about a quarterback.
  boxColumns: [
    ["comp", "COMP"], ["att", "ATT"], ["pass_yds", "PASS"], ["pass_tds", "PTD"],
    ["carries", "CAR"], ["rush_yds", "RUSH"], ["rush_tds", "RTD"],
    ["rec", "REC"], ["rec_yds", "RECYD"], ["rec_tds", "RECTD"],
    ["ints", "INT"], ["fumbles", "FUM"], ["fgs", "FG"],
  ],

  /**
   * A football box score is THREE tables, not one.
   *
   * A quarterback, a cornerback and a kicker share almost no columns. Flat, the
   * table gave each of them a row that was two-thirds dashes, which is why
   * football's box score read as empty however well anyone played.
   *
   * TOTAL YDS leads the offensive table and is DERIVED, never stored: it is
   * one man's passing plus rushing plus receiving. It is display-only and must
   * never be summed into a team total - the team's passing yards already ARE
   * its receivers' receiving yards, so adding these up would count every yard
   * twice.
   *
   * The defensive table shows only what the ledger honestly produces. The
   * simulation records interceptions and forced fumbles by unit; it does not
   * model tackles or individual sacks, so there are no columns for them. An
   * empty column would be a claim we cannot support.
   */
  boxGroups: [
    {
      key: "offense",
      label: "Offense",
      slots: ["QB", "RB", "WR", "TE", "OL", "FLEX"],
      columns: [
        ["total_yds", "TOT YDS", (line) =>
          (Number(line.pass_yds) || 0) + (Number(line.rush_yds) || 0) + (Number(line.rec_yds) || 0)],
        ["comp", "COMP"], ["att", "ATT"], ["pass_yds", "PASS"], ["pass_tds", "PTD"],
        ["carries", "CAR"], ["rush_yds", "RUSH"], ["rush_tds", "RTD"],
        ["rec", "REC"], ["rec_yds", "RECYD"], ["rec_tds", "RECTD"],
      ],
      // Total yards first, touchdowns as the tie-break - scaled so a score is
      // worth a hundred yards rather than swamping the yardage entirely.
      rank: (line) =>
        (Number(line.pass_yds) || 0) + (Number(line.rush_yds) || 0) + (Number(line.rec_yds) || 0) +
        100 * ((Number(line.pass_tds) || 0) + (Number(line.rush_tds) || 0) + (Number(line.rec_tds) || 0)),
    },
    {
      key: "defense",
      label: "Defense",
      slots: ["DL", "LB", "CB", "S", "DEF"],
      columns: [["ints", "INT"], ["fumbles", "FUM"]],
      rank: (line) => (Number(line.ints) || 0) * 2 + (Number(line.fumbles) || 0),
    },
    {
      key: "kicking",
      label: "Kicking",
      slots: ["ST"],
      columns: [["fgs", "FG"], ["fga", "FGA"]],
      rank: (line) => Number(line.fgs) || 0,
    },
  ],
  // Deliberately none. A football box score is read by position - quarterback,
  // then backs, then receivers - not ranked by who scored most, and re-sorting
  // it at the final buzzer put the kicker above the quarterback whenever he
  // outscored him. Shared code falls back to orderedRosterSlots when this is
  // null, which for football is LINEUP_ORDER.
  sortBoxBy: null,
  cardStatLine: (p) => {
    const n = (v, d = 1) => (Number(v) || 0).toFixed(d);
    if (p.group) {
      // Lead the line with a name you know. "Cornerbacks" is a slot; "Sherman,
      // Maxwell" is the pick - and since any member's name claims the unit,
      // showing them is also showing what you are allowed to type.
      const known = (p.members || []).slice(0, 2).map((m) => m.name).join(", ");
      const depth = known ? `${known} · ${p.depth} deep` : `${p.depth} deep`;
      if (p.group === "ST") return `${depth} · ${n(100 * (p.fg_pct || 0), 0)}% FG · ${n(p.fg_att)} att`;
      if (p.group === "OL") return `${depth} · ${n(p.sacks_allowed)} sk allowed · ${n(p.ypc)} ypc`;
      return `${depth} · ${n(p.tackles)} tkl · ${n(p.sacks)} sk · ${n(p.ints, 2)} int`;
    }
    const pos = (p.pos || [])[0];
    if (pos === "QB") return `${n(p.pass_yds, 0)} pass yds · ${n(p.pass_td, 1)} TD · ${n(p.ints, 1)} INT`;
    if (pos === "RB") return `${n(p.rush_yds, 0)} rush yds · ${n(p.rush_td)} TD · ${n(p.rec)} rec`;
    return `${n(p.rec)} rec · ${n(p.rec_yds, 0)} yds · ${n(p.rec_td)} TD`;
  },
  basePosition: (slot) => slot.replace(/\d+$/, ""),
  isBenchSlot: (slot) => slot.startsWith("BENCH"),
  // Lineup order, not draft order. Object.keys() hands back the order the
  // slots were FILLED, so a roster drafted WR-first printed its box score
  // WR, RB, TE, QB - which reads as a mistake, because no football box score
  // has ever opened on a wide receiver. Anything not in the list (a slot a
  // future mode adds) keeps its relative position at the end rather than
  // disappearing.
  orderedRosterSlots: (roster) => {
    const filled = Object.keys(roster).filter((s) => roster[s]);
    const rank = (slot) => {
      const i = LINEUP_ORDER.indexOf(slot);
      return i === -1 ? LINEUP_ORDER.length : i;
    };
    return filled.sort((a, b) => rank(a) - rank(b) || filled.indexOf(a) - filled.indexOf(b));
  },
  minutesRangeFor: () => ({ min: 0, max: 0 }),
  rotationBudget: 0,

  // Narrative and grading. Stubs live in the sibling files named below; these
  // throw for the same reason the simulation stubs do - a recap that returned
  // empty prose would look like a working game with nothing to say.
  buildRecap: (result, rosterA, rosterB, labelA, labelB) =>
    buildRecap(result, rosterA, rosterB, labelA, labelB),
  // Passed through, not re-wrapped. The wrapper took only the first argument
  // and dropped the two team names behind it, so football's final line read
  // "undefined and undefined finish level at 15.94". NBA hands the function
  // over directly, which is why only football lost the names.
  buildGameScript,
  buildPostGameAnalysis: (result, side) => buildPostGameAnalysis(result, side),
  // Named gradeDraft because that is what shared code calls (js/main.js).
  // NFL exposed it as draftGrade and would have thrown the moment a football
  // draft finished - caught by scripts/verify-sport-contract.mjs, which exists
  // for exactly this class of mismatch.
  // Nothing to hint at - football has no rotation to advise on. Returns null
  // rather than being absent, because shared code calls it unconditionally.
  rotationHint: () => null,
  gradeDraft: (roster, ctx, forfeits) => draftGrade(roster, ctx ?? NFL.computeDatasetStats(), forfeits),
  rotationHint: () => null,
  // Football's counterpart to basketball's counterplay read: how your roster
  // stacks against theirs, side of the ball by side of the ball.
  draftAnalysis: (roster, oppRoster, ctx, forfeits) =>
    draftGrade(roster, ctx ?? NFL.computeDatasetStats(), forfeits),
  shotLine: () => null,
  formatShotLine: () => "",

  // The ladder and the explanation are real even though the game is not -
  // they are the two screens you can look at today, and there is nothing
  // stopping them being finished.
  tiers: TIERS,
  howToPlay: HOW_TO_PLAY,

  // TWO decisions, not one. Football asks how you attack and how you defend
  // separately, so the sport declares GROUPS and shared UI renders a section
  // per group. A sport with no strategyGroups keeps the single-card picker,
  // which is what basketball still uses.
  strategyGroups: STRATEGY_GROUPS,
  defaultStrategy: DEFAULT_STRATEGY,
  normalizeStrategy,
  planFor,
  plansFor,
  randomStrategy,
  formatStrategy,
  serializeStrategy,
  parseStrategy,

  // The single-plan surface shared code still reaches for. Pointed at the
  // OFFENSIVE catalogue rather than removed: a caller that has not learned
  // about groups yet gets a real, coherent list of football plans instead of
  // undefined. Anything that matters reads strategyGroups.
  tactics: OFFENSIVE_PLANS,
  defaultTactic: DEFAULT_STRATEGY.offense,
  tacticById: (id) => planFor("offense", id),
  randomTacticChoices: () => [...OFFENSIVE_PLANS],
  defensivePlans: DEFENSIVE_PLANS,

  /** What still has to exist before `live` can flip. Rendered on the locked
   * tile in dev builds, so the remaining work is visible in the product
   * rather than only in this comment. */
  todo: [
    "Import per-game player data into an nfl_players table",
    "Aggregate defensive position groups into draftable units (units.js)",
    "Author era brackets that follow rule changes, not decades",
    "Write a drive-based simulation engine and calibrate it",
    "Author gamestyles and solve their multipliers the way tactics.js is",
    "Add NFL badges and make the franchise banners earnable",
  ],
};

export default NFL;
