// Shared chrome for the legal pages: the top bar, the document switcher, the
// "last updated" stamp and the footer.
//
// The document TEXT is static HTML inside each page on purpose - legal text
// has to render with JavaScript off, be linkable at a stable URL, and be
// readable by a crawler or a court without a runtime. Only the surrounding
// furniture is built here, so there is one copy of it rather than seven.
//
// The same reasoning drives [data-legal-field]: each page ships the real
// address as literal text (so it reads correctly with no JS), and this module
// overwrites it from js/legal/config.js on load, so changing the contact
// address in one file changes it everywhere without leaving the no-JS reader
// looking at a placeholder.
import { LEGAL, LEGAL_DOCUMENTS } from "./config.js";
import { initBrandImages } from "../brand-image.js";

const root = document.querySelector("[data-legal-page]");

if (root) {
  const activeId = root.dataset.legalPage;
  fillFields();
  document.body.prepend(buildHeader());
  const nav = buildDocumentNav(activeId);
  if (nav) root.prepend(nav);
  stampUpdated();
  document.body.append(buildFooter());
  // After the header is in the document, so the image it built is findable.
  initBrandImages();
}

/** Literal addresses in the markup are the no-JS fallback; config wins. */
function fillFields() {
  for (const el of document.querySelectorAll("[data-legal-field]")) {
    const value = LEGAL[el.dataset.legalField];
    if (value === undefined) {
      // A typo'd field name would otherwise silently leave stale text on a
      // legal page, which is the exact failure this indirection exists to
      // prevent - so say so rather than leaving it alone.
      console.error(`Unknown legal field: ${el.dataset.legalField}`);
      continue;
    }
    el.textContent = String(value);
    if (el.tagName === "A" && el.getAttribute("href")?.startsWith("mailto:")) {
      el.setAttribute("href", `mailto:${value}`);
    }
  }
}

function buildHeader() {
  const header = document.createElement("header");
  header.className = "top-nav";

  const brand = document.createElement("a");
  brand.className = "brand";
  brand.href = "../index.html";
  // No inline onerror here either: these pages carry the same CSP the app
  // does. initBrandImages() runs after the header is in the document.
  brand.innerHTML =
    '<img class="brand-mark" src="../assets/brand/draft-nova-icon.png" alt="" data-brand-fallback="hide" />' +
    '<span class="brand-word">Draft Nova</span>';

  const back = document.createElement("a");
  back.className = "nav-tab";
  back.href = "../index.html";
  back.textContent = "Back to the game";

  header.append(brand, back);
  return header;
}

function buildDocumentNav(activeId) {
  const nav = document.createElement("nav");
  nav.className = "legal-doc-nav";
  nav.setAttribute("aria-label", "Legal documents");
  for (const doc of LEGAL_DOCUMENTS) {
    if (doc.id === activeId) {
      const current = document.createElement("span");
      current.className = "legal-doc-link active";
      current.setAttribute("aria-current", "page");
      current.textContent = doc.title;
      nav.append(current);
    } else {
      const link = document.createElement("a");
      link.className = "legal-doc-link";
      link.href = doc.path;
      link.textContent = doc.title;
      nav.append(link);
    }
  }
  return nav;
}

/** One stamp per page, written from config so a revision can't update six of
 * seven documents and leave the seventh claiming to be current. */
function stampUpdated() {
  for (const el of document.querySelectorAll("[data-legal-updated]")) {
    el.textContent = `Version ${LEGAL.VERSION} — last updated ${LEGAL.LAST_UPDATED}`;
  }
}

function buildFooter() {
  const footer = document.createElement("footer");
  footer.className = "app-footer";
  const links = LEGAL_DOCUMENTS.map((d) => `<a href="${d.path}">${d.title}</a>`).join("");
  footer.innerHTML =
    `<div class="app-footer-links">${links}</div>` +
    `<p class="app-footer-note">Draft Nova is a simulation game. Results are generated by a computer model and are not real games. ` +
    `Not affiliated with the NBA, NFL, NBPA, NFLPA or any of their teams.</p>`;
  return footer;
}
