// Every name, address and date the legal documents depend on, in one place.
//
// Six documents plus the in-app consent line all quote the same operator,
// the same contact address and the same governing law. Six copies of that
// would be six things to update the day the company and the domain exist -
// and a privacy policy that names a contact nobody reads is worse than one
// that names none at all, because it looks like a promise.
//
// TODO(legal): before launch, and certainly before charging anyone money -
//   1. OPERATOR_LEGAL_NAME: replace with the registered entity once it exists.
//   2. CONTACT_EMAIL and friends: move to addresses on the real domain.
//   3. SITE_URL: the production domain, not the github.io fallback.
//   4. Register the DMCA agent with the US Copyright Office ($6). Safe harbour
//      does NOT attach without that registration, no matter what dmca.html says.
//   See docs/legal-checklist.md for the full list.

export const LEGAL = {
  // What the service is called, and who is answerable for it. Until an entity
  // is registered these are the same string; the documents ask for them
  // separately so that day is a one-line change.
  SERVICE_NAME: "Draft Nova",
  OPERATOR_LEGAL_NAME: "Draft Nova",

  // A reachable human is the part that actually matters legally. A pretty
  // address on a matching domain is the part that matters commercially.
  CONTACT_EMAIL: "maxwell@gurrbrothers.com",
  PRIVACY_EMAIL: "maxwell@gurrbrothers.com",
  DMCA_EMAIL: "maxwell@gurrbrothers.com",

  SITE_URL: "https://madams3432923943.github.io/gamebuild/",

  GOVERNING_LAW: "the State of Delaware, United States",
  VENUE: "the state and federal courts located in the State of Delaware",

  // 13 is the COPPA line: under-13s are barred outright, so the service never
  // has to run verifiable-parental-consent machinery. Users in the EU/UK who
  // are under 16 need a parent's consent - see the children's section of the
  // privacy policy.
  MIN_AGE: 13,
  GDPR_CONSENT_AGE: 16,

  // Deletion is promised in two places (self-serve button, emailed request);
  // this is the window the privacy policy commits to for the emailed path.
  DELETION_SLA_DAYS: 30,

  // Bumped whenever a document's substance changes - not for typo fixes.
  // Shown on each page, and the value a stored consent record would pin to.
  VERSION: "1.1",
  LAST_UPDATED: "August 13, 2026",
};

// The one-liner shown under simulated results and in the sign-up card. Lives
// here because the AI disclosure page, the game screen and the how-to-play
// modal must not drift into saying three slightly different things.
export const SIMULATION_NOTICE =
  "Simulated result. Every score, stat line and recap in Draft Nova is generated by " +
  "a computer model - it is not a record of any real game.";

export const AFFILIATION_NOTICE =
  "Draft Nova is not affiliated with, endorsed by, or sponsored by the NBA, the NFL, " +
  "the NBPA, the NFLPA, or any of their teams. Player names and statistics are real " +
  "historical facts, used to identify the athletes they describe.";

// The documents, in the order they are listed everywhere they are listed.
// `path` is relative to the legal/ directory, which is where every consumer
// of this list currently lives.
export const LEGAL_DOCUMENTS = [
  { id: "terms", path: "terms.html", title: "Terms of Service", blurb: "The rules for using Draft Nova, and the limits on our liability." },
  { id: "privacy", path: "privacy.html", title: "Privacy Policy", blurb: "What we collect, why, who processes it, and how to get it deleted." },
  { id: "community", path: "community.html", title: "Community Guidelines", blurb: "What is and isn't allowed in usernames, squad names and mottos." },
  { id: "ai", path: "ai-disclosure.html", title: "AI & Simulation Disclosure", blurb: "Results are simulated, not real. Where AI was and wasn't used." },
  { id: "disclaimers", path: "disclaimers.html", title: "Disclaimers & Attribution", blurb: "No league affiliation, where the data comes from, no betting advice." },
  { id: "dmca", path: "dmca.html", title: "Copyright / DMCA", blurb: "How to report infringing content and how to counter a report." },
  { id: "accessibility", path: "accessibility.html", title: "Accessibility", blurb: "The standard we build to, known gaps, and how to tell us about one." },
];
