// Writes the NFL dataset out as SQL for the server's `nfl_players` table.
//
// The football counterpart to tools/export-players-sql.mjs, and it exists for
// the same reason: ~14,000 rows is megabytes of INSERT statements, and any
// route that pushes them through a chat context or a hand-run query is a route
// where a name gets mangled or a batch silently vanishes. A half-loaded table
// is worse than an empty one - the draft finds some of a player's seasons and
// not others, with no error anywhere to say so.
//
// WHY ONE TABLE FOR TWO KINDS OF THING
//
// nfl_players holds both players and units (a team's cornerbacks in a given
// season), distinguished by `kind`. That is the shape the table was created
// with in db/migrations/20260731_04_nfl_players.sql and the shape the Edge
// Function reads, so it is reproduced here rather than argued with.
//
// `payload` carries the whole row as jsonb and the columns beside it are
// denormalised copies for filtering. Both come from the same object, so they
// cannot disagree.
//
// Output is idempotent - delete, then insert - so re-running after a dataset
// rebuild converges instead of accumulating duplicates. The delete and the
// inserts are wrapped in a transaction so a failure leaves the previous rows
// in place: a draft against stale players is wrong, a draft against no players
// is dead.
//
// Usage:  node tools/export-nfl-sql.mjs
//         then apply db/seed/nfl-seed.sql (see tools/apply-seed.mjs)

import { writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { ROWS as PLAYERS } from "../data/nfl-players.js";
import { ROWS as UNITS } from "../data/nfl-units.js";

const here = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(here, "..", "db", "seed");
const OUT = join(OUT_DIR, "nfl-seed.sql");

/** Postgres string literal. Doubling the quote is the whole escape rule, and
 * names like "Ka'imi Fairbairn" are exactly why this cannot be skipped. */
const lit = (s) => `'${String(s).replace(/'/g, "''")}'`;
const arr = (a) => `ARRAY[${(a || []).map(lit).join(",")}]::text[]`;
const n = (v) => (v === null || v === undefined || Number.isNaN(v) ? "NULL" : String(v));
/** jsonb literal. The payload is the row itself, so whatever the build script
 * produces reaches the server unedited - no field list to fall behind. */
const json = (o) => `${lit(JSON.stringify(o))}::jsonb`;

const rows = [
  ...PLAYERS.map((p) => ({
    kind: "player",
    unit_group: null,
    name: p.name,
    team: p.team,
    era: p.era,
    season: p.season,
    pos: p.pos,
    payload: p,
  })),
  ...UNITS.map((u) => ({
    kind: "unit",
    unit_group: u.group,
    name: u.name,
    team: u.team,
    era: u.era,
    season: u.season,
    pos: u.pos,
    payload: u,
  })),
];

const COLUMNS = ["kind", "unit_group", "name", "team", "era", "season", "pos", "payload"];

const values = rows.map(
  (r) =>
    `(${lit(r.kind)},${r.unit_group === null ? "NULL" : lit(r.unit_group)},${lit(r.name)},` +
    `${lit(r.team)},${lit(r.era)},${n(r.season)},${arr(r.pos)},${json(r.payload)})`
);

// Chunked because a single statement with 14,000 tuples is awkward for any
// client to stream and impossible to read when one row is malformed.
const CHUNK = 500;
const statements = [];
for (let i = 0; i < values.length; i += CHUNK) {
  statements.push(
    `insert into public.nfl_players (${COLUMNS.join(", ")}) values\n` +
      values.slice(i, i + CHUNK).join(",\n") +
      ";"
  );
}

const seasons = [...new Set(PLAYERS.map((p) => p.season))].sort();

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(
  OUT,
  `-- Generated by tools/export-nfl-sql.mjs from data/nfl-players.js and\n` +
    `-- data/nfl-units.js. Do not hand-edit: re-run the script.\n` +
    `--\n` +
    `-- ${PLAYERS.length} player-seasons and ${UNITS.length} units, ` +
    `seasons ${seasons[0]}-${seasons[seasons.length - 1]}.\n` +
    `--\n` +
    `-- Wrapped in a transaction so a failure leaves the old rows in place\n` +
    `-- rather than an empty table.\n\n` +
    `begin;\n\ndelete from public.nfl_players;\n\n${statements.join("\n\n")}\n\ncommit;\n`
);

console.log(
  `${PLAYERS.length} players + ${UNITS.length} units = ${rows.length} rows ` +
    `(${seasons[0]}-${seasons[seasons.length - 1]}) -> ${OUT}`
);
