// Writes the NFL dataset out as SQL for the server's `nfl_players` table.
//
// The football counterpart to tools/export-players-sql.mjs, and it exists for
// the same reason: ~14,000 rows is megabytes of INSERT statements, and any
// route that pushes them through a chat context or a hand-run query is a route
// where a name gets mangled or a batch silently vanishes. A half-loaded table
// is worse than an empty one - the draft finds some of a player's seasons and
// not others, with no error anywhere to say so.
//
// WHY ONE TABLE FOR TWO KINDS OF THING
//
// nfl_players holds both players and units (a team's cornerbacks in a given
// season), distinguished by `kind`. That is the shape the table was created
// with in db/migrations/20260731_04_nfl_players.sql and the shape the Edge
// Function reads, so it is reproduced here rather than argued with.
//
// `payload` carries the whole row as jsonb and the columns beside it are
// denormalised copies for filtering. Both come from the same object, so they
// cannot disagree.
//
// Output is idempotent - stage, then publish - so re-running after a dataset
// rebuild converges instead of accumulating duplicates.
//
// THE LIVE TABLE IS NEVER EMPTY WHILE THIS RUNS.
//
// It used to be. The file was `delete from nfl_players` followed by ~30 chunked
// inserts, and tools/apply-seed.mjs sends each statement to the Management API
// separately - one connection each - so a begin/commit wrapper grouped nothing
// and had to be stripped. The delete committed alone and the pool was gone for
// about a minute. An online football match started in that window found no
// players, and because every rating is a percentile against the pool it was
// computed from, an empty pool does not throw: it rates everything 0.5 and
// produces a plausible, wrong game.
//
// The inserts now fill public.nfl_players_staging, which nothing reads, and a
// single call to publish_nfl_players_from_staging() moves it across. One
// statement is one implicit transaction, so the swap is atomic and a failure
// leaves the previous dataset in place. See
// db/migrations/20260820_01_atomic_dataset_publish.sql - including why the
// rename swap this comment used to recommend would have been a bug.
//
// Usage:  node tools/export-nfl-sql.mjs
//         then apply db/seed/nfl-seed.sql (see tools/apply-seed.mjs)

import { writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { loadDataset } from "../data/load.mjs";
import { nflSeedRows } from "./lib/seed-rows.mjs";

const PLAYERS = await loadDataset("nfl-players");
const UNITS = await loadDataset("nfl-units");

const here = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(here, "..", "db", "seed");
const OUT = join(OUT_DIR, "nfl-seed.sql");

/** Postgres string literal. Doubling the quote is the whole escape rule, and
 * names like "Ka'imi Fairbairn" are exactly why this cannot be skipped. */
const lit = (s) => `'${String(s).replace(/'/g, "''")}'`;
const arr = (a) => `ARRAY[${(a || []).map(lit).join(",")}]::text[]`;
const n = (v) => (v === null || v === undefined || Number.isNaN(v) ? "NULL" : String(v));
/** jsonb literal. The payload is the row itself, so whatever the build script
 * produces reaches the server unedited - no field list to fall behind. */
const json = (o) => `${lit(JSON.stringify(o))}::jsonb`;

// The row shape lives in tools/lib/seed-rows.mjs, not here. It had three
// copies - this file, the basketball exporter, and the Edge Function handler
// test - and tools/bake-server-stats.mjs now precomputes the rating context
// FROM these rows, so a projection that drifts would bake statistics against
// one shape and serve them against another.
const rows = await nflSeedRows();

const COLUMNS = ["kind", "unit_group", "name", "team", "era", "season", "pos", "payload"];

const values = rows.map(
  (r) =>
    `(${lit(r.kind)},${r.unit_group === null ? "NULL" : lit(r.unit_group)},${lit(r.name)},` +
    `${lit(r.team)},${lit(r.era)},${n(r.season)},${arr(r.pos)},${json(r.payload)})`
);

// Chunked because a single statement with 14,000 tuples is awkward for any
// client to stream and impossible to read when one row is malformed.
const CHUNK = 500;
const statements = [];
for (let i = 0; i < values.length; i += CHUNK) {
  statements.push(
    `insert into public.nfl_players_staging (${COLUMNS.join(", ")}) values\n` +
      values.slice(i, i + CHUNK).join(",\n") +
      ";"
  );
}

const seasons = [...new Set(PLAYERS.map((p) => p.season))].sort();

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(
  OUT,
  `-- Generated by tools/export-nfl-sql.mjs from data/nfl-players.json and\n` +
    `-- data/nfl-units.json. Do not hand-edit: re-run the script.\n` +
    `--\n` +
    `-- ${PLAYERS.length} player-seasons and ${UNITS.length} units, ` +
    `seasons ${seasons[0]}-${seasons[seasons.length - 1]}.\n` +
    `--\n` +
    `-- Staged, then published in one statement, so public.nfl_players goes\n` +
    `-- straight from the old dataset to the new one with nothing in between.\n\n` +
    `truncate table public.nfl_players_staging;\n\n` +
    `${statements.join("\n\n")}\n\n` +
    `select public.publish_nfl_players_from_staging();\n`
);

console.log(
  `${PLAYERS.length} players + ${UNITS.length} units = ${rows.length} rows ` +
    `(${seasons[0]}-${seasons[seasons.length - 1]}) -> ${OUT}`
);
