// Stamps index.html's entry import AND its stylesheet with the current commit,
// so a deploy always serves fresh JS and fresh CSS - and writes the
// <link rel="modulepreload"> block that flattens the boot waterfall.
//
// GitHub Pages sets no cache-busting headers and browsers cache ES modules
// aggressively. Every fix in a run of four bug reports was already live and
// already correct - the browser was serving the previous build, and there was
// no way to tell that from the outside. A changing query string ends it.
//
// The stylesheet was left unversioned for a long time, which was survivable
// only while CSS changes were rare and cosmetic. It stopped being survivable
// the moment a feature shipped its own styles: the shot chart's markers are
// invisible without them, so a returning browser holding a cached stylesheet
// would draw a basketball game with nothing on the court and no error to
// explain it. Same commit for both, so one deploy is one version.
//
// Run by `npm run verify`, so the stamp cannot drift from what is committed.

import { readFileSync, writeFileSync, existsSync } from "fs";
import { execSync } from "child_process";
import { join, dirname, posix } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const file = join(root, "index.html");

// ---------------------------------------------------------------------------
// The module preload block
// ---------------------------------------------------------------------------
//
// WHAT IT FIXES. The browser cannot ask for js/ui/format.js until it has
// fetched and parsed js/main.js, js/ui.js and js/ui/profile.js - it does not
// know the file exists before that. Measured over a 45ms link, boot was ELEVEN
// serial round trips of that discovery for 52 modules that are all needed
// unconditionally, and the connection sat idle through most of them. A
// modulepreload tag tells the browser about a module before anything has
// imported it, so all 52 go out in the first round instead of the eleventh.
//
// WHY IT IS GENERATED. A hand-written list of 52 paths is a list that is wrong
// the first time somebody adds a module - and wrong in the silent direction: a
// missing entry is not an error, it is just the old waterfall back for that
// branch. This runs on every `npm run verify`, so the block cannot drift from
// the graph it describes.
//
// STATIC IMPORTS ONLY. A dynamic `import()` is deliberately deferred work -
// the sport datasets, the football engine, supabase-js - and preloading one
// would undo the lazy loading that took NBA and NFL off the boot path in the
// first place. Only what main.js pulls in unconditionally is listed here.

const PRELOAD_START = "  <!-- MODULEPRELOAD:START (generated by tools/stamp-build.mjs - do not edit) -->";
const PRELOAD_END = "  <!-- MODULEPRELOAD:END -->";

/** Static import/export specifiers in one module's source.
 *
 * Deliberately a regex and not a parser. The alternative is a dependency on a
 * JS parser in a repo that has no build step, to read import statements that
 * are all written the same way; `import(` is excluded by requiring whitespace
 * or a quote where the parenthesis would be, which is what keeps the lazy
 * imports off this list. */
function staticImportsIn(source) {
  const specs = [];
  // `import ... from "x"`, `export ... from "x"`, and bare `import "x"`.
  const re = /(?:^|[\n;])\s*(?:import|export)\s+(?:[^'"()]*?\sfrom\s+)?['"]([^'"]+)['"]/g;
  let m;
  while ((m = re.exec(source))) specs.push(m[1]);
  return specs;
}

/** Every module reachable from the entry by static import, in the order a
 * browser would discover them. Relative specifiers only: a bare specifier is
 * the import map's business (supabase-js), and it is preloaded by its own tag
 * in the head rather than from here. */
function moduleGraph(entryRel) {
  const seen = new Set([entryRel]);
  const ordered = [];
  const queue = [entryRel];
  while (queue.length) {
    const rel = queue.shift();
    const abs = join(root, rel);
    if (!existsSync(abs)) continue;
    for (const spec of staticImportsIn(readFileSync(abs, "utf8"))) {
      if (!spec.startsWith(".")) continue;
      const resolved = posix.normalize(posix.join(posix.dirname(rel), spec));
      if (seen.has(resolved)) continue;
      seen.add(resolved);
      ordered.push(resolved);
      queue.push(resolved);
    }
  }
  return ordered;
}

/** The block, as the lines it occupies in the head.
 *
 * NO VERSION QUERY, and that is not an oversight. main.js is fetched as
 * `js/main.js?v=<sha>` but its own imports resolve WITHOUT one - `./sound.js`
 * is `js/sound.js`, not `js/sound.js?v=<sha>`. A preload href has to be
 * byte-identical to the URL the module graph will request or the browser
 * fetches the file twice: once for the hint, once for the import. */
function preloadBlock(modules) {
  return [
    PRELOAD_START,
    ...modules.map((m) => `  <link rel="modulepreload" href="${m}" />`),
    PRELOAD_END,
  ].join("\n");
}

const sha = execSync("git rev-parse --short HEAD", { cwd: root }).toString().trim();
const html = readFileSync(file, "utf8");
let stamped = html
  .replace(/(src="js\/main\.js\?v=)[^"]*(")/, `$1${sha}$2`)
  // Tolerates the stylesheet being unversioned the first time, and re-stamps
  // it every time after.
  .replace(/(href="css\/style\.css)(\?v=[^"]*)?(")/, `$1?v=${sha}$3`);

const modules = moduleGraph("js/main.js");
const block = preloadBlock(modules);
// The markers are found by index rather than by regex: they are fixed strings
// containing parentheses and a hyphen, and escaping them into a pattern is
// fussier than indexOf, which is all this needs.
const startAt = stamped.indexOf(PRELOAD_START);
const endAt = stamped.indexOf(PRELOAD_END);
if (startAt !== -1 && endAt !== -1) {
  stamped = stamped.slice(0, startAt) + block + stamped.slice(endAt + PRELOAD_END.length);
} else {
  console.error(
    "No MODULEPRELOAD:START/END markers in index.html - the preload block could not be written. " +
      "Boot still works; it is just back to discovering modules one round trip at a time."
  );
}

if (stamped === html) {
  console.log(`build stamp already ${sha}; ${modules.length} modules preloaded`);
} else {
  writeFileSync(file, stamped);
  console.log(`build stamp -> ${sha}; ${modules.length} modules preloaded`);
}
